baseurl = "http://steakneggermuskegon.com/"
languageCode = "en-us"
title = "Steak 'N Egger"
googleanalytics = ""
copyright = "© 2020 Steak N Egger. All Rights Reserved"
disableKinds=["RSS"]

[params]
  description = "Steak N Egger, a family owned breakfast, lunch, and dinner restaurant and eatery focused on energetic atmosphere and engaging service."
  about = "Serving Muskegon since 1977, Steak 'N Egger continues to be a local favorite for breakfast and lunch alike. Under new ownership since December 2015, we look forward to continuing the rich tradition of the almost four decades of providing quality food and service. Our full menu is available anytime and includes a wide array of classic American comfort food. Our completely remodeled interior is both warm and welcoming for catching up with an old friend or stopping for a quick bite on your way through town."
  keywords = "american restaurant,breakfast restaurant,restaurant,breakfast,muskegon,watch muskegon, steak and egger, steak n egger"
  facebook = "SteakandEgger"
  fbpageID = "567889869937615"
  twitter = ""
  instagram = "steakneggermuskegon"
  email = "sjb@steakneggermuskegon.com"
  phone = "(231) 719-8939"
  address1 = "1535 Holton Rd"
  address2 = "Muskegon, Michigan 49445"
  googlemaps = "https://goo.gl/maps/DnbcPgZQMgQ2"

[[params.hours]]
  days = "Monday-Friday"
  hours = "7am-3pm"
[[params.hours]]
  days = "Saturday & Sunday"
  hours = "7am-2pm"